# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/wander
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn run cov:check
      - codecov/upload:
          file: "coverage"
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/wander
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn run cov:check
      - codecov/upload:
          file: "coverage"
workflows:
  version: 2.1
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
