# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/wander
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - persist_to_workspace:
          root: "."
          paths:
              - src
              - build
              - yarn.lock
  "node-latest":
    docker:
      - image: circleci/node:latest
    working_directory: ~/wander
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-latest"
